### PR TITLE
changed github actions to fix CSV build deploy

### LINKED ISSUE #24: Compat bounds in Project.toml
Hello,

I stumbled upon this repo after reading your issue with Pkg compats on Slack. I feel  your pain, these clashes can  be super annoying.  One q: (1) did you try putting  Franklin in your toml? and if that failed (2) did  you try putting compat bounds explicitly in the Project.toml of your site folder instead of putting those in the  deploy script? 

The chain of dependencies that cause the problems described  on  Slack is

```
Franklin -> Literate ->  JSON -> Parsers
```

and then that clashes with CSV which requires Parsers  1, I think. But when you put everything in your Project.toml file (including Franklin), it should get the right versions for everything.

PS: pretty  cool website, I wasn't  aware of it :)

### PR DESCRIPTION
**Pull request by storopoli**
Fixes #24

### CODE REVIEW

**Comment by storopoli** [comment]
@tlienart GHA is running.

**Comment by tlienart** [comment]
I think you'll be one of the users made very happy with the caching stuff that's coming to Franklin soon ;-)

**Comment by storopoli** [comment]
> I think you'll be one of the users made very happy with the caching stuff that's coming to Franklin soon ;-)

Wow what is that? I have been following Franklin and Literate releases but I have not heard of the "catching stuff" before...

**Comment by tlienart** [comment]
no that's normal; I'm basically working on a very significant refactoring of Franklin which will end up being the `1.0` version; from the user perspective almost nothing will change in terms of the syntax etc, but the parser will be much better, it will support common mark, things will be cached so it will be much faster etc... this is non trivial work though, I'm maybe 70% of the way :-) there's no announcement anywhere as it's not there yet :joy: though if you're interested I can ping you to be one of the beta testers when the whole thing works.

**Comment by tlienart** [comment]
PS: did it work?

**Comment by storopoli** [comment]
> PS: did it work?
Yes! It did! Thanks!

> though if you're interested I can ping you to be one of the beta testers when the whole thing works.
Yes of course! I would love to beta test. Happy to contribute with Franklin.jl.

**Pull request merged**
