### PR TITLE
Set GKSwstype: nul

### PR DESCRIPTION
**Pull request by rikhuijzer**
Your logs contain many plotting errors and setting `GKSwstype: nul` will fix this. Also, it will improve running speed and how the output looks.

### CODE REVIEW

**Comment by storopoli** [comment]
Amazing! Thanks! I was aware of that but I had no idea how to fix that! 🚀

**Comment by rikhuijzer** [comment]
You're welcome. You can also checkout https://github.com/StatisticalRethinkingJulia/TuringModels.jl for tips and tricks (or hacks :stuck_out_tongue:). That one is also built with Franklin.

**Comment by storopoli** [comment]
I guess this would also be good?

```yml
# To reduce state.
clean: true
# To save space; we don't really need older versions.
single-commit: true
```

**Comment by rikhuijzer** [comment]
I did that because I once had a bug which took very long to track down. Eventually, it turned out that I wasn't generating some image, but that I was looking at an image from 3 deploys ago. So, that's why I added those lines indeed. 

The downside is that you will lose the possibility to inspect previous versions which would be bad for things like Documenter.jl.

**Pull request merged**
